# Exemplo de arquivo secrets para o Streamlit.
# Copie este arquivo para .streamlit/secrets.toml e preencha com seus valores.
# NUNCA faça commit do arquivo secrets.toml no Git!

MENSAGEM = "Sua mensagem personalizada aqui"

[minha_config]
CHAVE_API = "sua-chave-de-api"
MODO_DEBUG = true
